/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dictionary_swing;

import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class ReplaceWordDialog extends javax.swing.JFrame {

    /**
     * Creates new form ReplaceWordDialog
     */
    public ReplaceWordDialog() {
        initComponents();
        this.setLocationRelativeTo(null);
        setTitle("Chức năng sửa từ");
        
        int i = MainForm.binarySearch(MainForm.wordNeedReplacing);
        oldWord.setText(MainForm.wordNeedReplacing);
        oldMean.setText(Dictionary.dictionary.get(i).getWord_explain());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        replace = new javax.swing.JButton();
        newWord = new javax.swing.JTextField();
        mean = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        exitProgram = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        oldWord = new javax.swing.JLabel();
        oldMean = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        replace.setText("Sửa");
        replace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                replaceMouseClicked(evt);
            }
        });
        replace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                replaceActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Từ mới");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Dịch nghĩa");

        exitProgram.setText("Thoát");
        exitProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitProgramActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Từ cũ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(replace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                .addComponent(exitProgram)
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(newWord, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(oldMean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mean)
                    .addComponent(oldWord, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(oldWord, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(oldMean, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newWord, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mean, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(exitProgram)
                    .addComponent(replace))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitProgramActionPerformed
        this.dispose();
    }//GEN-LAST:event_exitProgramActionPerformed

    private void replaceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_replaceMouseClicked
        String newWord = this.newWord.getText().toLowerCase();
        String mean = this.mean.getText().toLowerCase();
        if (newWord.equals("") || mean.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Chưa nhập đủ thông tin!\nXin nhập lại");
        } else if (checkString(newWord) == false) {
            JOptionPane.showMessageDialog(rootPane, "Không hợp lệ!\nXin nhập lại");
        } else if (MainForm.binarySearch(newWord) > -1 && MainForm.wordNeedReplacing.equals(newWord) == false) {           //Kiểm tra từ mới trùng
            JOptionPane.showMessageDialog(rootPane, "Từ đã tồn tại\nXin nhập lại");
        } else {
            Dictionary dic = new Dictionary();
            int choose = JOptionPane.showConfirmDialog(rootPane, "Bạn chắc chắn muốn sửa?");
            if (choose == JOptionPane.YES_OPTION) {
                int i = MainForm.binarySearch(MainForm.wordNeedReplacing);
                Dictionary.dictionary.set(i, new Word(newWord, mean));
                dic.dictionaryExportToFile();           //Change to file
                JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
                this.dispose();                             //Close scene
            }
        }
    }//GEN-LAST:event_replaceMouseClicked

    private void replaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_replaceActionPerformed
        String newWord = this.newWord.getText().toLowerCase();
        String mean = this.mean.getText().toLowerCase();
        if (newWord.equals("") || mean.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Chưa nhập đủ thông tin!\nXin nhập lại");
        } else if (checkString(newWord) == false) {
            JOptionPane.showMessageDialog(rootPane, "Không hợp lệ!\nXin nhập lại");
        } else if (MainForm.binarySearch(newWord) > -1 && MainForm.wordNeedReplacing.equals(newWord) == false) {           //Kiểm tra từ mới trùng
            JOptionPane.showMessageDialog(rootPane, "Từ đã tồn tại\nXin nhập lại");
        } else {
            Dictionary dic = new Dictionary();
            int choose = JOptionPane.showConfirmDialog(rootPane, "Bạn chắc chắn muốn sửa?");
            if (choose == JOptionPane.YES_OPTION) {
                int i = MainForm.binarySearch(MainForm.wordNeedReplacing);
                Dictionary.dictionary.set(i, new Word(newWord, mean));
                dic.dictionaryExportToFile();           //Change to file
                JOptionPane.showMessageDialog(rootPane, "Sửa thành công");
                this.dispose();                             //Close scene
            }
        }
    }//GEN-LAST:event_replaceActionPerformed

    private boolean checkString(String input) {
        for (int i = 0; i < input.length(); i++) {
            if (input.charAt(i) > 47 && input.charAt(i) < 58) {
                return false;
            }
        }
        return true;
    }   //Check input new word has number

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ReplaceWordDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ReplaceWordDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ReplaceWordDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ReplaceWordDialog.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ReplaceWordDialog().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitProgram;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField mean;
    private javax.swing.JTextField newWord;
    private javax.swing.JLabel oldMean;
    private javax.swing.JLabel oldWord;
    private javax.swing.JButton replace;
    // End of variables declaration//GEN-END:variables
}
